"""Add method and status_code to audit_logs

Revision ID: 523c10e139f0
Revises: 1972b509107d
Create Date: 2025-09-26 17:37:07.965760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523c10e139f0'
down_revision: Union[str, Sequence[str], None] = '1972b509107d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'status_code')
    # ### end Alembic commands ###
