"""Add method, path, status_code, timestamp, user_agent to audit_logs

Revision ID: d570f7deebcc
Revises: 523c10e139f0
Create Date: 2025-09-26 17:39:30.246115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd570f7deebcc'
down_revision: Union[str, Sequence[str], None] = '523c10e139f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
